name: bounded

num_target_views: 1
num_context_views: 4

min_distance_between_context_views: 1
max_distance_between_context_views: 4
min_distance_to_context_views: 0

warm_up_steps: 0
initial_min_distance_between_context_views: 1
initial_max_distance_between_context_views: 4

max_img_per_gpu: 5
min_gap_multiplier: 1
max_gap_multiplier: 1